service: upload-binary

plugins:
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 3008
  timeout: 10
  stage: dev
  region: us-east-1

custom:
  apigwBinary:
    types:
      - 'image/*'

functions:
  api:
    handler: handler.index
    events:
      - http:
          path: 'upload'
          method: post
          cors: true